/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:d1a8fd16-4904-4827-b553-82e22304379e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_sLivncQZO",
    "aws_user_pools_web_client_id": "2p4u193ua9u0df3qq4qi1hrc8p",
    "oauth": {}
};


export default awsmobile;
 